### ISSUE TITLE
Fix outdated info in doc/session.txt

### ISSUE THREAD

**Issue by matjon** [xolox/vim-session#108]
Hello,
In doc/session.txt ( https://github.com/xolox/vim-session/blob/master/doc/session.txt#L515 ) it is written:

        Recently this plug-in switched from reimplementing |:mksession| to actually
        using it because this was the only way to support complex split window layouts.
        Only after making this change did I realize |:mksession| doesn't support
        |quickfix| and location list (see |location-list|) windows and of course it
        turns out that bolting on support for these after the fact is going to
        complicate the plug-in significantly (in other words, I'm working on it but it
        might take a while...)

1) It was done in 2010, so it should be probably changed:
"Recently this plug-in" -> "In 2010 (commit a047591) this plug-in"
2) Quickfix seems to be implemented AFAIK, I don't know anything about the location list.

**Comment by xolox** [comment]
Thanks for pointing this out, this should indeed have been removed because it's been a long time since then :-). I just removed this from the documentation in the git repository. The next release will no longer include the paragraph.
