### ISSUE TITLE
Enhancement Request: Disable Session Lock

### ISSUE THREAD

**Issue by alexdunn** [xolox/vim-session#112]
I'd really like to disable the session lock with a setting.  I don't care about having a session open in more than one place.  It becomes a pain when I kill the terminal app, thus unsafely killing vim and failing to remove the session lock, so all the subsequent auto session opens will give a failure.

**Comment by xolox** [comment]
I believe [the option I just added](http://peterodding.com/code/vim/session#session_lock_enabled_option) answers your question. Can you confirm?

**Comment by alexdunn** [comment]
Yes, that's exactly it!  Thanks!
