### ISSUE TITLE
session doesn't auto save and auto load

### ISSUE THREAD

**Issue by syswow** [xolox/vim-session#113]
Hello, 
I have put 
```
let g:session_autosave=1
let g:session_autoload=1
```
in my .vimrc. but nothing changed. :question:

**Comment by blurm** [comment]
Same problem here. May i ask how did you solve this problem?

**Comment by syswow** [comment]
@blurm 
session conflict with some plugins. try to disable them all, then re-enable one by one.

**Comment by xolox** [comment]
@syswow and @blurm: A suggestion to improve the documentation to make things easier for newcomers is welcome (e.g. about conflicts with specific plug-ins). It doesn't have to be a pull request, you can also just suggest an addition in a message here and I'll consider adding it to the documentation.
