### ISSUE TITLE
Error detected while processing

### ISSUE THREAD

**Issue by gerroon** [xolox/vim-session#118]
Error detected while processing ....../session.vim:
line   53:
E325: ATTENTION

And the line 53 is 

52 argglobal
53 edit somesourcefile.extension
54 let s:l = 14 - ((13 * winheight(0) + 36) / 72)

I obfuscated the names and the paths. The files exist.

This is a tab session.

thanks

**Comment by xolox** [comment]
This is an error emitted by Vim itself, not the vim-session plug-in. If you execute the Vim command `:help E325` you'll get an explanation about how Vim swap files work and where the [E325 ATTENTION message](http://vimdoc.sourceforge.net/htmldoc/usr_11.html#E325) is coming from.

**Comment by xolox** [comment]
A quick follow up: I don't believe the vim-session plug-in should have special handling for this, so unless you want to convince me otherwise :-) I don't consider this a problem that should be solved by the vim-session plug-in. Does this explanation resolve your issue?

**Comment by gerroon** [comment]
@xolox 

Thanks for your explanation. Fair enough.
