### ISSUE TITLE
Make the saving of guifont optional.

### ISSUE THREAD

**Issue by jszakmeister** [xolox/vim-session#128]
I don't really change fonts that often, but a few times I've ended up tweaking my default font selection on several systems that have goofy setups.  This is generally done by editing my ~/.vimrc.  Because sessions persist the font setting, it doesn't carry over to my saved sessions.  It would be nice if I could disable the setting of guifont and let my vimrc's choice win.

**Comment by xolox** [comment]
Hi John and thanks for the feedback!

I just released vim-session 2.13 which adds support for the [g:session_persist_font](https://github.com/xolox/vim-session#the-gsession_persist_font-option) option.

I believe this new option resolves your problem so I'm going to close this issue. If the new option doesn't work (well) for you then feel free to reopen this issue or create a new one.

Happy Vimming!

**Comment by jszakmeister** [comment]
Thank you Peter!  I tried out the feature and it seems to be working well!  Thanks again!
