### ISSUE TITLE
--servername is working with gvim but not with vim (macvim)

### ISSUE THREAD

**Issue by maurizzzio** [xolox/vim-session#134]
Thanks for making `vim-session` :D it's really really useful

I'm trying to start vim with a session I saved with the name `dotfiles`, If I execute

```sh
gvim --servername dotfiles
```

It works, however this doesn't

```sh
vim --servername dotfiles
```

Info related with my version of vim

```sh
❯ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 31 2015 17:27:39)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew
```

**Comment by xolox** [comment]
[I don't think this is even possible](http://vim.1045645.n5.nabble.com/Is-it-possible-to-start-MacVim-without-GUI-but-as-server-td4718233.html). What you can do instead though:

```
vim -c 'OpenSession dotfiles'
```

I hope this is an acceptable workaround because I don't think you have any other choices :-).

**Comment by maurizzzio** [comment]
It works! thanks for the quick response and again for making `vim-session` :D
