### ISSUE TITLE
Auto completion seems wrong

### ISSUE THREAD

**Issue by Ploppz** [xolox/vim-session#135]
I have two sessions, physics and graphic. When I write `:OpenSession ph` and press TAB, it auto completes as graphic.

**Comment by Cypher1** [comment]
I think this is a vim completion thing not vim-session.
Vim is seeing the ph in graphic (graphic comes before physics in a sorted list).

I'd recommend looking up other fuzzy finders (like fzf) or maybe just typing phy.

Good luck

**Comment by Ploppz** [comment]
Alright, thanks.
