### ISSUE TITLE
Provide a single autocommand after session is loaded

### ISSUE THREAD

**Issue by blueyed** [xolox/vim-session#141]
There is `SessionLoadPost` already, but it gets executed for each buffer/window.

I would like to have a callback to adjust settings according to the loaded session, e.g. `viminfo` / `shada` (Neovim), but dislike the overhead of it being called X times.

**Comment by mMontu** [comment]
What about disabling the autocmd on the first execution?

```
  augroup MySessionLoadPost
    autocmd!
    au SessionLoadPost * call SessionLoadPostSettings()
  augroup END

  function! SessionLoadPostSettings()
     " my settings (...)
     au! MySessionLoadPost
  endfunction
```

**Comment by blueyed** [comment]
@mMontu 
Good idea, thanks!
