### ISSUE TITLE
A buffer sometimes remains in buffer list even though I close it (delete it, wipe it, make sure it doesn't exist in :buffers) and save session

### ISSUE THREAD

**Issue by sassanh** [xolox/vim-session#145]
In a clean session when I
- open a buffer
- save session
- close vim
- open vim
- load session
  the buffer is not listed in buffers list. But in my big sessions that I've been using for few months when I
- remove a buffer (with `:bd`)
- check `:ls` to make sure it's removed
- save session
- close vim
- open vim
- load that session
  the buffer is still present in `:ls`I
- removed the buffer
- saved session
- opened session file (the ,vim file associated with that session)
  and saw that there's a line containing that filename like this:
  
  argadd path/to/file

This is the only place the file is mentioned in this file. Any idea what's going on here?

**Comment by romgrk** [comment]
Fastest way to get rid of the buffer I found until now: switch to the persistent buffer and do `argdel %`.
