### ISSUE TITLE
The 'default' session is locked by another Vim instance

### ISSUE THREAD

**Issue by benwoodward** [xolox/vim-session#87]
In my .vimrc I have;

```
let g:session_autoload="yes"
let g:session_autosave="yes"
```

On booting MacVim (installed via homebrew, with https://github.com/carlhuda/janus installed) I get;

```
session.vim 2.4.9: The 'default' session is locked by another Vim instance named VIM.
```

Here is my Activity Monitor window..

![screen shot 2014-03-20 at 11 31 52](https://f.cloud.github.com/assets/1472981/2467818/1d054bea-afc7-11e3-880a-6af5c228c882.png)

The mysterious VIM instance always appears. I boot MacVim via the `mvim` command from Terminal. The same issue occurs when using vanilla `vim` inside Terminal.

**Comment by nayzawoo** [comment]
:OpenSession! default
